# Generated by Django 3.0.4 on 2020-04-21 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile_org',
            name='is_org',
            field=models.BooleanField(default=False),
        ),
    ]
