# Generated by Django 3.0.4 on 2020-04-21 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_profile_org_is_org'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile_org',
            name='department',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='profile_org',
            name='roll_number',
            field=models.CharField(default='', max_length=100),
        ),
    ]
