# Generated by Django 3.0.4 on 2020-04-17 05:11

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('educational', 'educational'), ('fun', 'fun'), ('sports', 'sports'), ('party', 'party'), ('other', 'other')], max_length=100),
        ),
    ]
