# Generated by Django 3.0.4 on 2020-04-22 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_auto_20200422_1137'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='bookmarks',
        ),
    ]
